version: 2
project:
  project_id: "project_id"
  name: "Test Project"
pages:
  - type: section
    title: "Section"
    children:
      # Explicit link and title
      - type: markdown
        lang:
          en:
            title: "File1 EN"
            link: "file1_en"
            filepath: "file1.en.md"
          ja:
            title: "File1 JA"
            link: "file1_ja"
            filepath: "file1.ja.md"
      # Implicit link and title
      - type: markdown
        lang:
          en:
            filepath: "file2.en.md"
          ja:
            filepath: "file2.ja.md"
  - type: directory
    title: "Docs"
    children:
      - type: match
        pattern: "directory/*.md"
        sort_key: "title"
        sort_order: "asc"
